// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto // import "github.com/roderm/audio-panel/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ac1e0d5639bf3e38, []int{0}
}
func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (dst *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(dst, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type AVR struct {
	Id                   int64               `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Power                bool                `protobuf:"varint,2,opt,name=Power" json:"Power,omitempty"`
	Zones                map[int32]*AVR_Zone `protobuf:"bytes,3,rep,name=Zones" json:"Zones,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InputSources         map[int32]string    `protobuf:"bytes,4,rep,name=InputSources" json:"InputSources,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IP                   string              `protobuf:"bytes,5,opt,name=IP" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AVR) Reset()         { *m = AVR{} }
func (m *AVR) String() string { return proto.CompactTextString(m) }
func (*AVR) ProtoMessage()    {}
func (*AVR) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ac1e0d5639bf3e38, []int{1}
}
func (m *AVR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AVR.Unmarshal(m, b)
}
func (m *AVR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AVR.Marshal(b, m, deterministic)
}
func (dst *AVR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AVR.Merge(dst, src)
}
func (m *AVR) XXX_Size() int {
	return xxx_messageInfo_AVR.Size(m)
}
func (m *AVR) XXX_DiscardUnknown() {
	xxx_messageInfo_AVR.DiscardUnknown(m)
}

var xxx_messageInfo_AVR proto.InternalMessageInfo

func (m *AVR) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AVR) GetPower() bool {
	if m != nil {
		return m.Power
	}
	return false
}

func (m *AVR) GetZones() map[int32]*AVR_Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

func (m *AVR) GetInputSources() map[int32]string {
	if m != nil {
		return m.InputSources
	}
	return nil
}

func (m *AVR) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type AVR_Zone struct {
	State                bool     `protobuf:"varint,1,opt,name=State" json:"State,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Volume               int32    `protobuf:"varint,3,opt,name=Volume" json:"Volume,omitempty"`
	IsMain               bool     `protobuf:"varint,4,opt,name=isMain" json:"isMain,omitempty"`
	Muted                bool     `protobuf:"varint,8,opt,name=Muted" json:"Muted,omitempty"`
	Source               int32    `protobuf:"varint,5,opt,name=Source" json:"Source,omitempty"`
	SyncVol              bool     `protobuf:"varint,6,opt,name=SyncVol" json:"SyncVol,omitempty"`
	SyncSrc              bool     `protobuf:"varint,7,opt,name=SyncSrc" json:"SyncSrc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AVR_Zone) Reset()         { *m = AVR_Zone{} }
func (m *AVR_Zone) String() string { return proto.CompactTextString(m) }
func (*AVR_Zone) ProtoMessage()    {}
func (*AVR_Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ac1e0d5639bf3e38, []int{1, 0}
}
func (m *AVR_Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AVR_Zone.Unmarshal(m, b)
}
func (m *AVR_Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AVR_Zone.Marshal(b, m, deterministic)
}
func (dst *AVR_Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AVR_Zone.Merge(dst, src)
}
func (m *AVR_Zone) XXX_Size() int {
	return xxx_messageInfo_AVR_Zone.Size(m)
}
func (m *AVR_Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_AVR_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_AVR_Zone proto.InternalMessageInfo

func (m *AVR_Zone) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

func (m *AVR_Zone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AVR_Zone) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *AVR_Zone) GetIsMain() bool {
	if m != nil {
		return m.IsMain
	}
	return false
}

func (m *AVR_Zone) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

func (m *AVR_Zone) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *AVR_Zone) GetSyncVol() bool {
	if m != nil {
		return m.SyncVol
	}
	return false
}

func (m *AVR_Zone) GetSyncSrc() bool {
	if m != nil {
		return m.SyncSrc
	}
	return false
}

type AVR_PowerToggle struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
	On                   bool     `protobuf:"varint,2,opt,name=On" json:"On,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AVR_PowerToggle) Reset()         { *m = AVR_PowerToggle{} }
func (m *AVR_PowerToggle) String() string { return proto.CompactTextString(m) }
func (*AVR_PowerToggle) ProtoMessage()    {}
func (*AVR_PowerToggle) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ac1e0d5639bf3e38, []int{2}
}
func (m *AVR_PowerToggle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AVR_PowerToggle.Unmarshal(m, b)
}
func (m *AVR_PowerToggle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AVR_PowerToggle.Marshal(b, m, deterministic)
}
func (dst *AVR_PowerToggle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AVR_PowerToggle.Merge(dst, src)
}
func (m *AVR_PowerToggle) XXX_Size() int {
	return xxx_messageInfo_AVR_PowerToggle.Size(m)
}
func (m *AVR_PowerToggle) XXX_DiscardUnknown() {
	xxx_messageInfo_AVR_PowerToggle.DiscardUnknown(m)
}

var xxx_messageInfo_AVR_PowerToggle proto.InternalMessageInfo

func (m *AVR_PowerToggle) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *AVR_PowerToggle) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

type ZoneUpdate struct {
	AVR_IP               string   `protobuf:"bytes,1,opt,name=AVR_IP,json=AVRIP" json:"AVR_IP,omitempty"`
	Zone_Name            string   `protobuf:"bytes,2,opt,name=Zone_Name,json=ZoneName" json:"Zone_Name,omitempty"`
	State                bool     `protobuf:"varint,3,opt,name=State" json:"State,omitempty"`
	Volume               int32    `protobuf:"varint,4,opt,name=Volume" json:"Volume,omitempty"`
	Source               int32    `protobuf:"varint,5,opt,name=Source" json:"Source,omitempty"`
	SyncVol              bool     `protobuf:"varint,6,opt,name=SyncVol" json:"SyncVol,omitempty"`
	SyncSrc              bool     `protobuf:"varint,7,opt,name=SyncSrc" json:"SyncSrc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneUpdate) Reset()         { *m = ZoneUpdate{} }
func (m *ZoneUpdate) String() string { return proto.CompactTextString(m) }
func (*ZoneUpdate) ProtoMessage()    {}
func (*ZoneUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ac1e0d5639bf3e38, []int{3}
}
func (m *ZoneUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneUpdate.Unmarshal(m, b)
}
func (m *ZoneUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneUpdate.Marshal(b, m, deterministic)
}
func (dst *ZoneUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneUpdate.Merge(dst, src)
}
func (m *ZoneUpdate) XXX_Size() int {
	return xxx_messageInfo_ZoneUpdate.Size(m)
}
func (m *ZoneUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneUpdate proto.InternalMessageInfo

func (m *ZoneUpdate) GetAVR_IP() string {
	if m != nil {
		return m.AVR_IP
	}
	return ""
}

func (m *ZoneUpdate) GetZone_Name() string {
	if m != nil {
		return m.Zone_Name
	}
	return ""
}

func (m *ZoneUpdate) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

func (m *ZoneUpdate) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *ZoneUpdate) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *ZoneUpdate) GetSyncVol() bool {
	if m != nil {
		return m.SyncVol
	}
	return false
}

func (m *ZoneUpdate) GetSyncSrc() bool {
	if m != nil {
		return m.SyncSrc
	}
	return false
}

func init() {
	proto.RegisterType((*Null)(nil), "null")
	proto.RegisterType((*AVR)(nil), "AVR")
	proto.RegisterMapType((map[int32]string)(nil), "AVR.InputSourcesEntry")
	proto.RegisterMapType((map[int32]*AVR_Zone)(nil), "AVR.ZonesEntry")
	proto.RegisterType((*AVR_Zone)(nil), "AVR.Zone")
	proto.RegisterType((*AVR_PowerToggle)(nil), "AVR_PowerToggle")
	proto.RegisterType((*ZoneUpdate)(nil), "ZoneUpdate")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AVRService service

type AVRServiceClient interface {
	GetAVRs(ctx context.Context, in *Null, opts ...grpc.CallOption) (AVRService_GetAVRsClient, error)
	Power(ctx context.Context, in *AVR_PowerToggle, opts ...grpc.CallOption) (*AVR, error)
	UpdateZone(ctx context.Context, in *ZoneUpdate, opts ...grpc.CallOption) (*ZoneUpdate, error)
	Subscribe(ctx context.Context, in *AVR, opts ...grpc.CallOption) (AVRService_SubscribeClient, error)
}

type aVRServiceClient struct {
	cc *grpc.ClientConn
}

func NewAVRServiceClient(cc *grpc.ClientConn) AVRServiceClient {
	return &aVRServiceClient{cc}
}

func (c *aVRServiceClient) GetAVRs(ctx context.Context, in *Null, opts ...grpc.CallOption) (AVRService_GetAVRsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_AVRService_serviceDesc.Streams[0], c.cc, "/AVRService/GetAVRs", opts...)
	if err != nil {
		return nil, err
	}
	x := &aVRServiceGetAVRsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AVRService_GetAVRsClient interface {
	Recv() (*AVR, error)
	grpc.ClientStream
}

type aVRServiceGetAVRsClient struct {
	grpc.ClientStream
}

func (x *aVRServiceGetAVRsClient) Recv() (*AVR, error) {
	m := new(AVR)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aVRServiceClient) Power(ctx context.Context, in *AVR_PowerToggle, opts ...grpc.CallOption) (*AVR, error) {
	out := new(AVR)
	err := grpc.Invoke(ctx, "/AVRService/Power", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aVRServiceClient) UpdateZone(ctx context.Context, in *ZoneUpdate, opts ...grpc.CallOption) (*ZoneUpdate, error) {
	out := new(ZoneUpdate)
	err := grpc.Invoke(ctx, "/AVRService/UpdateZone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aVRServiceClient) Subscribe(ctx context.Context, in *AVR, opts ...grpc.CallOption) (AVRService_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_AVRService_serviceDesc.Streams[1], c.cc, "/AVRService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &aVRServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AVRService_SubscribeClient interface {
	Recv() (*AVR, error)
	grpc.ClientStream
}

type aVRServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *aVRServiceSubscribeClient) Recv() (*AVR, error) {
	m := new(AVR)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AVRService service

type AVRServiceServer interface {
	GetAVRs(*Null, AVRService_GetAVRsServer) error
	Power(context.Context, *AVR_PowerToggle) (*AVR, error)
	UpdateZone(context.Context, *ZoneUpdate) (*ZoneUpdate, error)
	Subscribe(*AVR, AVRService_SubscribeServer) error
}

func RegisterAVRServiceServer(s *grpc.Server, srv AVRServiceServer) {
	s.RegisterService(&_AVRService_serviceDesc, srv)
}

func _AVRService_GetAVRs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Null)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AVRServiceServer).GetAVRs(m, &aVRServiceGetAVRsServer{stream})
}

type AVRService_GetAVRsServer interface {
	Send(*AVR) error
	grpc.ServerStream
}

type aVRServiceGetAVRsServer struct {
	grpc.ServerStream
}

func (x *aVRServiceGetAVRsServer) Send(m *AVR) error {
	return x.ServerStream.SendMsg(m)
}

func _AVRService_Power_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AVR_PowerToggle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AVRServiceServer).Power(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AVRService/Power",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AVRServiceServer).Power(ctx, req.(*AVR_PowerToggle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AVRService_UpdateZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AVRServiceServer).UpdateZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AVRService/UpdateZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AVRServiceServer).UpdateZone(ctx, req.(*ZoneUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _AVRService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AVR)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AVRServiceServer).Subscribe(m, &aVRServiceSubscribeServer{stream})
}

type AVRService_SubscribeServer interface {
	Send(*AVR) error
	grpc.ServerStream
}

type aVRServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *aVRServiceSubscribeServer) Send(m *AVR) error {
	return x.ServerStream.SendMsg(m)
}

var _AVRService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AVRService",
	HandlerType: (*AVRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Power",
			Handler:    _AVRService_Power_Handler,
		},
		{
			MethodName: "UpdateZone",
			Handler:    _AVRService_UpdateZone_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAVRs",
			Handler:       _AVRService_GetAVRs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _AVRService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_service_ac1e0d5639bf3e38) }

var fileDescriptor_service_ac1e0d5639bf3e38 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xd5, 0xfa, 0xab, 0xf1, 0x04, 0xd1, 0xb2, 0x94, 0x6a, 0x31, 0x07, 0xac, 0xa0, 0x22, 0x5f,
	0x70, 0x20, 0x5c, 0x50, 0x2f, 0xc8, 0x20, 0x84, 0x7c, 0x28, 0x8d, 0xd6, 0xe0, 0x43, 0x2f, 0x95,
	0x63, 0xaf, 0x82, 0x85, 0xe3, 0x8d, 0xd6, 0x76, 0x51, 0xfe, 0x02, 0x3f, 0x89, 0x23, 0xff, 0x86,
	0x7f, 0x81, 0x76, 0xd7, 0x49, 0x4c, 0xe0, 0xd8, 0x53, 0xf6, 0xcd, 0xbc, 0x7d, 0x99, 0x7d, 0x6f,
	0x0c, 0x0f, 0xd7, 0x82, 0xb7, 0x7c, 0xda, 0x30, 0x71, 0x5b, 0xe6, 0x2c, 0x54, 0x68, 0xe2, 0x80,
	0x55, 0x77, 0x55, 0x35, 0xf9, 0x6d, 0x82, 0x19, 0xa5, 0x14, 0xdf, 0x07, 0x23, 0x2e, 0x08, 0xf2,
	0x51, 0x60, 0x52, 0x23, 0x2e, 0xf0, 0x29, 0xd8, 0x73, 0xfe, 0x9d, 0x09, 0x62, 0xf8, 0x28, 0x18,
	0x51, 0x0d, 0xf0, 0x39, 0xd8, 0xd7, 0xbc, 0x66, 0x0d, 0x31, 0x7d, 0x33, 0x18, 0xcf, 0x8e, 0xc3,
	0x28, 0xa5, 0xa1, 0xaa, 0x7c, 0xa8, 0x5b, 0xb1, 0xa1, 0xba, 0x8b, 0x2f, 0xe0, 0x5e, 0x5c, 0xaf,
	0xbb, 0x36, 0xe1, 0x9d, 0xc8, 0x59, 0x43, 0x2c, 0xc5, 0x3e, 0x53, 0xec, 0x61, 0x43, 0x5f, 0xfa,
	0x8b, 0xab, 0x06, 0x99, 0x13, 0xdb, 0x47, 0x81, 0x4b, 0x8d, 0x78, 0xee, 0xfd, 0x42, 0x60, 0x49,
	0x55, 0x39, 0x51, 0xd2, 0x66, 0x2d, 0x53, 0x43, 0x8e, 0xa8, 0x06, 0x18, 0x83, 0xf5, 0x29, 0x5b,
	0x31, 0x35, 0xa6, 0x4b, 0xd5, 0x19, 0x9f, 0x81, 0x93, 0xf2, 0xaa, 0x5b, 0x31, 0x62, 0xfa, 0x28,
	0xb0, 0x69, 0x8f, 0x64, 0xbd, 0x6c, 0x2e, 0xb3, 0xb2, 0x26, 0x96, 0x92, 0xe8, 0x91, 0x54, 0xbe,
	0xec, 0x5a, 0x56, 0x90, 0x91, 0x56, 0x56, 0x40, 0xb2, 0xf5, 0x4c, 0x6a, 0x18, 0x9b, 0xf6, 0x08,
	0x13, 0x38, 0x4a, 0x36, 0x75, 0x9e, 0xf2, 0x8a, 0x38, 0x8a, 0xbf, 0x85, 0xdb, 0x4e, 0x22, 0x72,
	0x72, 0xb4, 0xef, 0x24, 0x22, 0xf7, 0xde, 0x03, 0xec, 0x5d, 0xc2, 0x27, 0x60, 0x7e, 0x63, 0x1b,
	0xf5, 0x0e, 0x9b, 0xca, 0x23, 0x7e, 0x0a, 0xf6, 0x6d, 0x56, 0x75, 0xfa, 0x19, 0xe3, 0x99, 0xbb,
	0xf3, 0x95, 0xea, 0xfa, 0x85, 0xf1, 0x06, 0x79, 0x6f, 0xe1, 0xc1, 0x3f, 0xe6, 0xfd, 0x47, 0xeb,
	0x74, 0xa8, 0xe5, 0x0e, 0x04, 0x26, 0xaf, 0xe0, 0x38, 0x4a, 0xe9, 0x8d, 0x8a, 0xf2, 0x33, 0x5f,
	0x2e, 0x2b, 0xd6, 0xbb, 0x8d, 0xb6, 0x6e, 0x4b, 0x7c, 0x55, 0xf7, 0x99, 0x1b, 0x57, 0xf5, 0xe4,
	0x27, 0xd2, 0x93, 0x7f, 0x59, 0x17, 0xd2, 0xed, 0x47, 0xe0, 0x48, 0x85, 0xdd, 0x15, 0x3b, 0x4a,
	0x69, 0x3c, 0xc7, 0x4f, 0xc0, 0x95, 0xa4, 0x9b, 0x41, 0x12, 0x23, 0x59, 0x50, 0x69, 0xec, 0x72,
	0x33, 0x87, 0xb9, 0xed, 0x33, 0xb2, 0x0e, 0x33, 0xba, 0x2b, 0xd7, 0x67, 0x3f, 0x10, 0x40, 0x94,
	0xd2, 0x44, 0x2f, 0xbe, 0x24, 0x7e, 0x64, 0x6d, 0x94, 0xd2, 0x06, 0xdb, 0xa1, 0x5c, 0x7e, 0xcf,
	0x92, 0x3e, 0xbf, 0x44, 0xd2, 0x7e, 0xbd, 0xdf, 0x27, 0xe1, 0x81, 0x41, 0x9a, 0x82, 0x9f, 0x03,
	0x68, 0x07, 0xd4, 0x26, 0x8e, 0xc3, 0xbd, 0x25, 0xde, 0x10, 0xe0, 0xc7, 0xe0, 0x26, 0xdd, 0xa2,
	0xc9, 0x45, 0xb9, 0x60, 0x58, 0x5d, 0xdd, 0xfe, 0xc7, 0xbb, 0xf3, 0xeb, 0x67, 0xcb, 0xb2, 0xfd,
	0xda, 0x2d, 0xc2, 0x9c, 0xaf, 0xa6, 0x82, 0x17, 0x4c, 0xac, 0xa6, 0x59, 0x57, 0x94, 0xfc, 0xc5,
	0x3a, 0xab, 0x59, 0x35, 0x55, 0xdf, 0xe5, 0xc2, 0x51, 0x3f, 0xaf, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x56, 0xbc, 0x11, 0x5d, 0xb5, 0x03, 0x00, 0x00,
}
